import { 
    EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV, 
    EXPO_PUBLIC_PACKAGE_ENV,
    EXPO_PUBLIC_VERSION_ENV,
    EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV,
    EXPO_PUBLIC_CDD_BASE_URL_ENV,
    EXPO_PUBLIC_MIS_BASE_URL_ENV,
    EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV,
    EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV,
    EXPO_PUBLIC_COUCHDB_BASE_URL_ENV,
    EXPO_PUBLIC_CDD_PLAYSTORE_URL_ENV,
    EXPO_PUBLIC_GRM_PLAYSTORE_URL_ENV,
    EXPO_MAPBOX_ACCESS_TOKEN_ENV,
    EXPO_PUBLIC_GRM_BASE_URL_ENV,
    EXPO_PUBLIC_GRM_DB_NAME_ENV
} from '@env'

const cddBaseURL = process.env.EXPO_PUBLIC_CDD_BASE_URL_ENV ?? EXPO_PUBLIC_CDD_BASE_URL_ENV;
export { cddBaseURL };

const misBaseURL = process.env.EXPO_PUBLIC_MIS_BASE_URL_ENV ?? EXPO_PUBLIC_MIS_BASE_URL_ENV;
export { misBaseURL };

const grmBaseURL = process.env.EXPO_PUBLIC_GRM_BASE_URL_ENV ?? EXPO_PUBLIC_GRM_BASE_URL_ENV;
export { grmBaseURL };

export const DIAGNOSTIC_MAP_LATITUDE = Number(process.env.EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV ?? EXPO_PUBLIC_DIAGNOSTIC_MAP_LATITUDE_ENV)
export const DIAGNOSTIC_MAP_LONGITUDE = Number(process.env.EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV ?? EXPO_PUBLIC_DIAGNOSTIC_MAP_LONGITUDE_ENV)

export const EXPO_PUBLIC_PACKAGE=process.env.EXPO_PUBLIC_PACKAGE_ENV ?? EXPO_PUBLIC_PACKAGE_ENV
export const EXPO_PUBLIC_ANDROID_VERSION_CODE=Number(process.env.EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV ?? EXPO_PUBLIC_ANDROID_VERSION_CODE_ENV)
export const EXPO_PUBLIC_VERSION=process.env.EXPO_PUBLIC_VERSION_ENV ?? EXPO_PUBLIC_VERSION_ENV
export const EXPO_PUBLIC_GOOGLEMAPS_APIKEY=process.env.EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV ?? EXPO_PUBLIC_GOOGLEMAPS_APIKEY_ENV
export const EXPO_PUBLIC_COUCHDB_BASE_URL=process.env.EXPO_PUBLIC_COUCHDB_BASE_URL_ENV ?? EXPO_PUBLIC_COUCHDB_BASE_URL_ENV
export const EXPO_PUBLIC_CDD_PLAYSTORE_URL=process.env.EXPO_PUBLIC_CDD_PLAYSTORE_URL_ENV ?? EXPO_PUBLIC_CDD_PLAYSTORE_URL_ENV
export const EXPO_PUBLIC_GRM_PLAYSTORE_URL=process.env.EXPO_PUBLIC_GRM_PLAYSTORE_URL_ENV ?? EXPO_PUBLIC_GRM_PLAYSTORE_URL_ENV
export const EXPO_MAPBOX_ACCESS_TOKEN=process.env.EXPO_MAPBOX_ACCESS_TOKEN_ENV ?? EXPO_MAPBOX_ACCESS_TOKEN_ENV;
export const GRM_DB_NAME=process.env.EXPO_PUBLIC_GRM_DB_NAME_ENV ?? EXPO_PUBLIC_GRM_DB_NAME_ENV;